# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

def pods_swift
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'PromiseKit'
  pod 'Texture'
  pod 'IGListKit'
  pod 'Alamofire'
  pod 'ObjectMapper'
  pod 'Kingfisher'
  pod 'lottie-ios'
  pod 'MBProgressHUD'
  # autolayout
  pod 'Cartography', '~> 1.1.0'
  pod 'SnapKit', '~> 3.2.0'
  pod 'TinyConstraints', '~> 2.1.1'
  # framelayout
  pod 'YogaKit'
  pod 'Neon', '~> 0.4.0'
  pod 'LayoutKit', '~> 5.0.0'
end

target 'ZDOpenSourceSwiftDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ZDOpenSourceSwiftDemo
  pods_swift
  
  target 'ZDOpenSourceSwiftDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ZDOpenSourceSwiftDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
