# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

def pods_swift
  # reactive
  pod 'RxSwift'
  pod 'RxCocoa'
  # promise
  pod 'PromiseKit'
  pod 'PromisesSwift'
  # optimize
  pod 'Texture'
  pod 'IGListKit'
  # network
  pod 'Alamofire'
  pod 'ObjectMapper'
  pod 'AlamofireObjectMapper'
  pod 'Kingfisher'
  pod 'ResponseDetective'
  # autolayout
  pod 'Cartography'
  pod 'SnapKit'
  pod 'TinyConstraints'
  # framelayout
  pod 'Yoga'
  pod 'YogaKit'
  pod 'Neon'
  pod 'LayoutKit'
  # animation
  pod 'lottie-ios'
  pod 'Hero'
  pod 'Gemini'
  # runtime
  pod 'RSSwizzle'
  # toast
  pod 'MBProgressHUD'
  pod 'Toast-Swift'
  # extensition
  
  # color
  pod 'ChameleonFramework/Swift'
  # tools
  pod 'DeepDiff' # 对比集合内元素是否变化
  pod 'GDPerformanceView-Swift'
  pod 'LifetimeTracker' # 监听内存泄露
  pod 'Watchdog'
  # debug
  pod 'Buglife'
  pod 'Peek', :configurations => ['Debug']
  pod 'FLEX', :configurations => ['Debug']
end

target 'ZDOpenSourceSwiftDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  inhibit_all_warnings!
  use_frameworks!

  # Pods for ZDOpenSourceSwiftDemo
  pods_swift
  
  target 'ZDOpenSourceSwiftDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ZDOpenSourceSwiftDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end
  
end


post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if target.name == 'LayoutKit'
                config.build_settings['SWIFT_VERSION'] = '4.1'
            end
        end
    end
end



