# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
#inhibit_all_warnings!

def pods_swift
  # reactive
  pod 'RxSwift'
  pod 'RxCocoa'
  # promise
  pod 'PromiseKit'
  # optimize
  pod 'Texture'
  pod 'IGListKit'
  # network
  pod 'Alamofire'
  pod 'ObjectMapper'
  pod 'AlamofireObjectMapper'
  pod 'Kingfisher'
  pod 'ResponseDetective'
  # autolayout
  pod 'Cartography'#, '~> 1.1.0'
  pod 'SnapKit'#, '~> 3.2.0'
  pod 'TinyConstraints'#, '~> 2.1.1'
  # framelayout
  pod 'YogaKit'
  pod 'Neon'#, '~> 0.4.0'
  pod 'LayoutKit'#, '~> 5.0.0'
  # animation
  pod 'lottie-ios'
  pod 'Hero'
  pod 'PeekPop'
  pod 'Gemini'
  pod 'MBProgressHUD'
  # extensition
  # tools
  pod 'GDPerformanceView-Swift'
end

target 'ZDOpenSourceSwiftDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  inhibit_all_warnings!
  use_frameworks!

  # Pods for ZDOpenSourceSwiftDemo
  pods_swift
  
  target 'ZDOpenSourceSwiftDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ZDOpenSourceSwiftDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
