# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

def pods_oc
  pod 'ReactiveObjC'
  pod 'JLRoutes'
  pod 'IGListKit'
  pod 'Texture'
  pod 'YogaKit'
  pod 'YYModel'
  pod 'YTKNetwork'
  pod 'Masonry'
  pod 'PromiseKit'
  pod 'KZPlayground'
end

target 'ZDOpenSourceOCDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for ZDOpenSourceOCDemo
  pods_oc

  target 'ZDOpenSourceOCDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ZDOpenSourceOCDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
