# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
inhibit_all_warnings!

def pods_git
    pod 'ZDTableViewBinding', :git => 'https://github.com/faimin/ZDTableViewBinding'
    pod 'ZDNetWorkHelper', :git => 'https://github.com/faimin/ZDNetWorkHelper'
    pod 'ZDToolKit', :git => 'https://github.com/faimin/ZDToolKit', :branch => 'develop'
end

def pods_oc
  # sync
  pod 'ReactiveObjC'
  pod 'PromiseKit'
  pod 'PromisesObjC'
  # layout
  pod 'IGListKit'
  pod 'Texture'
  pod 'YogaKit'
  pod 'Masonry'
  # router
  pod 'JLRoutes'
  # network
  pod 'YTKNetwork'
  pod 'YYModel'
  pod 'ResponseDetective'
  # animation
  pod 'lottie-ios'
  # tabbarController
  pod 'RDVTabBarController'
  pod 'RTRootNavigationController'
  # extension
  pod 'ObjectiveSugar', :inhibit_warnings => true
  pod 'LinqToObjectiveC'
  # injection
  pod 'libextobjc'
  pod 'Objection'
  pod 'Typhoon'
  pod 'ZIKRouter'
  # color
  pod 'ChameleonFramework'
  # toast
  pod 'SVProgressHUD'
  pod 'MBProgressHUD'
  pod 'Toast'
  # cache
  pod 'YYCache'
  # thread
  pod 'YYDispatchQueuePool'
  # runtime
  pod 'RSSwizzle'
  # tools
  pod 'GDPerformanceView'
  pod 'DirectoryWatchdog'
  # playground
  # pod 'KZPlayground', :inhibit_warnings => true
  # debug
  pod 'Buglife'
  pod 'FLEX', :configurations => 'Debug'
end

target 'ZDOpenSourceOCDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for ZDOpenSourceOCDemo
  pods_oc
  pods_git

  target 'ZDOpenSourceOCDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ZDOpenSourceOCDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end


post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            #config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO' #可以让pod中的类调用[UIApplication shareApplication]
            #关闭block内直接引用全局变量的警告
            config.build_settings['CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF'] = 'NO'
            if target.name == 'PromiseKit' || target.name == 'YogaKit' || target.name == 'ResponseDetective'
                config.build_settings['SWIFT_VERSION'] = '4.0'
            elsif target.name == 'ReactiveObjC'
                #关闭`This block declaration is not a prototype,Insert ‘void'`警告
                #config.build_settings['CLANG_WARN_STRICT_PROTOTYPES'] = 'NO'
            end
        end
    end
end

